# Generated by Django 5.0.6 on 2024-07-07 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_offer_period_offer_end_date_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99.99), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
